### PR TITLE
fix #29 by adding parameter

### LINKED ISSUE #29: ExtensionManagerService changed, causing RuntimeBinderException
```
System.Exception : Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: No overload for method 'UpdateLastExtensionsChange' takes '0' arguments
       at CallSite.Target(Closure , CallSite , Object )
       at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
       at VsixTesting.Installer.ExtensionManagerService.UpdateLastExtensionsChange()
       at VsixTesting.Installer.Installer.Install(String extensionPath, Nullable`1 allUsers)
       at VsixTesting.Installer.Installer.<>c__DisplayClass5_1.<Install>b__0(String path)
       at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
       at VsixTesting.Installer.Installer.Install(String applicationPath, String rootSuffix, IEnumerable`1 extensionPaths, Nullable`1 allUsers)
       at VsixTesting.Installer.Program.<>c__DisplayClass1_0.<Run>b__0()
       at VsixTesting.Installer.Program.Run(String applicationPath, String rootSuffix, String[] args)
  Stack Trace: 
    VisualStudioUtil.RunInstallerAsync(VsHive hive, IEnumerable<string> args) line 49
    VisualStudioUtil.InstallExtensionsAsync(VsHive hive, IEnumerable<string> extensions) line 18
    VsInstance+<>c__DisplayClass15_0+<<Prepare>b__0>d.MoveNext() line 54
    IDiagnosticsExtensions+<>c__DisplayClass1_0+<<RunAsync>b__0>d.MoveNext() line 34
    DiagnosticTestRunner<T>+<>c__DisplayClass5_0+<<RunAsync>b__0>d.MoveNext() line 182
    ExecutionTimer.AggregateAsync(Func<Task> asyncAction) line 48
    DiagnosticTestRunner<T>.RunAsync(IMessageBus messageBus, CancellationTokenSource cancellationTokenSource) line 180
    VsInstance.Prepare(VsHive hive, IEnumerable<string> extensionsToInstall, bool resetSettings, IDiagnostics diagnostics, bool installInvoker) line 41
    VsInstanceTestAssemblyRunner.Init(CancellationTokenSource cts) line 110
    VsInstanceTestAssemblyRunner.RunAsync(CancellationTokenSource cts) line 79
```

Apparently the method `ExtensionManagerService.UpdateLastExtensionsChange()` in `Microsoft.VisualStudio.ExtensionManager.Implementation.dll` (and therein used ones) changed and now take a bool named `updateClient`.
This results in the exception above, when running `VsFact`-TestMethods.

- Visual Studio Professional 2019 v16.7.2
- `Microsoft.VisualStudio.ExtensionManager.Implementation.dll` reports 'Date Modified' as 2020-08-13

### PR DESCRIPTION
**Pull request by LukasGelke**

### CODE REVIEW

File: src/VsixTesting.Installer/Program.cs [hunk 1]
```diff
@@ -329,7 +329,7 @@ public static IVsExtensionManager Create(ExternalSettingsManager externalSetting
         }
 
         public void UpdateLastExtensionsChange()
-            => Obj.UpdateLastExtensionsChange();
+            => Obj.UpdateLastExtensionsChange(true);
```
Comment (sharwell) [inline src/VsixTesting.Installer/Program.cs:332]: ❔ Is this still going to work with older versions?

Comment (LukasGelke) [reply src/VsixTesting.Installer/Program.cs:332]: I don't know. We don't have an old assembly version to test. Maybe they removed an overload, maybe they added the parameter.
Other than using package versions for that, could be to: try without parameter, catch (RuntimeBinderException) and to with parameter. Reflecting on that method if it has or has not any known parameters (0 or 1 bool) seems a bit overkill, if it would have no idea what to do in the else-branch anyway.

**Review by josetr — COMMENTED** [review]
VS2019 16.7.0 is the exact version where the method `UpdateLastExtensionsChange()` was removed. We can just check if `devenv.exe / ProductVersion` is equal or higher than 16.7 and if so call the new method. We've already used the ProductVersion twice so using it again seems fair play but `GetVersionInfo` is a bit expensive so we probably should store the result in a global variable and use it in all those 3 places.

**Review by josetr — APPROVED** [review]

**Comment by josetr** [comment]
VsixTesting.Xunit 0.1.54-beta contains your fix and is now available in nuget.org. 

Thanks 👍
